### ISSUE TITLE
remctl and processing of help and summary options

### ISSUE THREAD

**Issue by riton** [rra/remctl#3]
I was playing around with command such as https://github.com/rra/kadmin-remctl/blob/master/kadmin-backend that exposes an interface such as:

```
kadmin change_password [arguments]
kadmin create [arguments]
kadmin examine [arguments]
```

and I found myself face to a situation I didn't encounter in the past. This is actually the very first time that I'm dealing with commands that allow subcommands.

While setting up remctl configuration and setting up ACLs such as:

```
kadmin create ALL \
/usr/sbin/kadmin-backend \
princ:user_granted_create@EXAMPLE.FR

kadmin examine ALL \
/usr/sbin/kadmin-backend \
princ:user_granted_examine@EXAMPLE.FR
```

My wish was to create user friendlies summaries and helps for those commands. My users could then use

```
$ remctl HOSTNAME help
```

to discover all services they are granted access to. Till then, it's just classic _remctl_ use case.

Except that I can't find a way for each user to *only* see _summary_ and _help_ they only have access to.

**Summary**

as the doc said, for the _summary_ option _As mentioned above, this option is only meaningful on configuration lines with a subcommand of "ALL"._.
So that mean that I need to add a new configuration section like

```
kadmin ALL \
/usr/sbin/kadmin-backend \
summary=--summary \
princ:user_granted_create@EXAMPLE.FR \
princ:user_granted_examine@EXAMPLE.FR
```

at the end of my remctl configuration file that allows both users to access this _summary_ command.

By adding this, both users `user_granted_create@EXAMPLE.FR` and `user_granted_examine@EXAMPLE.FR` will be able to see the full summary (_create_ and _examine_ summary) and not the restricted version I'd like them to see.

There is no security concern here:
* user `user_granted_create@EXAMPLE.FR` will be able to see full summary. But he won't be able to access the `kadmin examine` command as the first remctl rule that matches denies him to.
* same for `user_granted_examine@EXAMPLE.FR`.

Such behavior could mislead users:
1. they fetch the remctl summary and sees all commands the server offers
2. they try a command but the server denies access to them

The "problem" here is that the _summary_ option is only effective if the subcommand is `ALL`

Don't you think that this could be a good idea to also interpret _summary_ option if a subcommand is specified ?
ACLs would then be evaluated when summary is called and each user should then really only see the commands he as access to.

I've created a quick and dirty patch (https://github.com/ccin2p3/remctl/compare/feature/summary_with_subcommand?expand=1) to illustrate this, in case my explanations were not very understandable.

Modifying things like this shouldn't introduce backward compatibility.

As the doc explicitly says that _summary_ is only pertinent for the `ALL` subcommand, maybe that I misunderstood something somewhere ...

**Comment by riton** [comment]
Hi @rra , is there anything keeping you away from the _merge_ button and close this issue ? This is getting quite old and everything seemed okay at the time.

**Comment by rra** [comment]
Yup, my fault -- changed jobs and haven't had a lot of time to work on open source projects, and this just slipped into my backlog and under my radar.  Now merged!

**Comment by riton** [comment]
Thanks !
